version: '3.5'
services:
   nginx-reverse-proxy:
      image: nginx:1.23
      volumes:
         - ./nginx/conf.d:/etc/nginx/conf.d
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./nginx/certs:/etc/nginx/certs
         - ./nginx/share/nginx/html:/usr/share/nginx/html
         - ./nginx/log:/var/log/nginx_log
      ports:
         # - "443:443"
         - "80:80"
      environment:
         - NGINX_HOST=localhost
         - NGINX_PORT=80
         - TZ=Asia/Bangkok
